=== twilight1794/tily-utils/misc/vcardbatch.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT vCardBatch (main,addres,comminication,hobbies,file)>
<!--Main//-->
<!ELEMENT main (name,2name,lname,born)>
<!ELEMENT name (#PCDATA) #REQUIRED>
<!ATTLIST name origin (CDATA|*)*>
<!ATTLIST name mean (CDATA|*)*>
<!ELEMENT 2name (#PCDATA) *>
<!ATTLIST 2name origin (CDATA|*) *>
<!ATTLIST 2name mean (CDATA|*) *>
<!ELEMENT lname (#PCDATA) #REQUIRED>
<!ATTLIST lname born (f-m|f-f|m-m) f-m>
<!ELEMENT born (day,month,year,hour,min)>
<!ATTLIST born number (NMTOKEN) 1>
<!ATTLIST born calendar (greg|world|sun|hol) greg>
<!ELEMENT day (CDATA|*) #REQUIRED>
<!ELEMENT month (CDATA|*) #REQUIRED>
<!ELEMENT year (CDATA|*) #REQUIRED>
<!ELEMENT hour (CDATA|*) *>
<!ELEMENT min (CDATA|*) *>
<!--Address//-->
<!ELEMENT address (street,numhouse,suburb,city,state,country)>
<!ELEMENT street (#PCDATA) *>
<!ELEMENT numhouse (NMTOKEN) *>
<!ATTLIST numhouse int (NMTOKEN) #IMPLIED)
<!ELEMENT suburb (#PCDATA) *>
<!ELEMENT city (NMTOKEN) *>
<!ELEMENT state (NMTOKEN) *>
<!ELEMENT country (NMTOKEN) *>
<!--Communication//-->
<!ELEMENT communication (email,tel,otherc)
<!ELEMENT email (homee,worke,cele,othere)
<!ELEMENT homee (#PCDATA) *>
<!ATTLIST homee server (Microsoft|Google|Yahoo) #IMPLIED>
<!ATTLIST homee service (Hotmail/Outlook|Gmail|Yahoo) #IMPLIED>
<!ELEMENT worke (#PCDATA) *>
<!ATTLIST worke server (Microsoft|Google|Yahoo) #IMPLIED>
<!ATTLIST worke service (Hotmail/Outlook|Gmail|Yahoo) #IMPLIED>
<!ELEMENT cele (#PCDATA) *>
<!ATTLIST cele server (Microsoft|Google|Yahoo) #IMPLIED>
<!ATTLIST cele service (Hotmail/Outlook|Gmail|Yahoo) #IMPLIED>
<!ELEMENT othere (#PCDATA) *>
<!ATTLIST othere server (Microsoft|Google|Yahoo) #IMPLIED>
<!ATTLIST othere service (Hotmail/Outlook|Gmail|Yahoo) #IMPLIED>
<!ELEMENT tel (celt,homet,nett,loct,othert)>
<!ELEMENT celt (NMTOKEN) *>
<!ELEMENT homet (NMTOKEN) *>
<!ELEMENT nett (NMTOKEN) *>
<!ELEMENT loct (NMTOKEN) *>
<!ELEMENT othert (NMTOKEN) *>
<!ELEMENT otherc (website)>
<!ELEMENT website (#PCDATA) *>
<!ATTLIST website ip (NMTOKEN|*) *>
<!--Hobbies//-->
<!ELEMENT hobbies (likes,activities,otherh)>
<!ELEMENT likes (music,art,sport,food,life,who,color,schedule,moreay)>
<!ELEMENT music (#PCDATA)>
<!ELEMENT art (#PCDATA)>
<!ELEMENT sport (#PCDATA)>
<!ELEMENT food (#PCDATA)>
<!ELEMENT life (#PCDATA)>
<!ELEMENT who (#PCDATA)>
<!ATTLIST who enc (Shift|ROT-16|XOR-224|ROT-13|B64|yEnc|Swap|Reverse|Block|Hex|Quoted-Printable|URL-Enc|HTML-Unicode|None) None>
<!ELEMENT color (#PCDATA)>
<!ELEMENT schedule (#PCDATA)>
<!ELEMENT moreay (#PCDATA)>
<!ELEMENT activities (preferences,projects)>
<!ELEMENT preferences (#PCDATA)>
<!ELEMENT projects (#PCDATA)>
<!ELEMENT otherh (#PCDATA)>
<!--File_Data//-->
<!ELEMENT file (progsrc,prog,instdir)>
<!ELEMENT progsrc>
<!ATTLIST progsrc gt (yes|no) #REQUIRED>
<!ELEMENT prog (#PCDATA)>
<!ATTLIST prog version (NMTOKEN) #REQUIRED>

<!ELEMENT instdir (#PCDATA)>

=== twilight1794/tily-utils/misc/xmlid.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE VCARDBATCH SYSTEM "http://giobeatle1794.esy.es/app_data/batch/pdk_1.0/vcardbatch.dtd">

<vCardBatch dtd="y">
<main>
	<name origin="italian" mean="Misericordia de Dios">Giovanny</name>
	<2name origin="greek" mean="PacÃ­fico">Alfredo</2name>
	<lname born="f-m">Garciliano Diaz</lname>
	<born num="1" calendar="greg">
		<day>20</day>
		<month>09</month>
		<year>2001</year>
		<hour>15</hour>
		<min>45</min>
	</born>
</main>
<address>
	<street type="c">Matamoros</street>
	<numhouse int="2">114</numhouse>
	<suburb zip="86120">Guadalupe Borja de D&iacute;az</suburb>
	<city>Villahermosa</city>
	<state>Tabasco</state>
	<country>M&eacute;xico</country>
</address>
<communication>
	<email>
		<homee server="Microsoft" service="Hotmail/Outlook">xivanni@hotmail.com</homee>
		<worke server="Google" service="Gmail">giobeatle10@gmail.com</workee>
		<cele server="*" service="*">*</cele>
		<othere server="*" service="*">*</othere>
	</email>
	<tel>
		<celt lade="52">9931954420</celt>
		<homet>*</homet>
		<nett>*</nett>
		<loct>*</loct>
		<othert>*</othert>
	</tel>
	<otherc>
		<website ip="31.170.165.6">http://giobeatle1794.esy.es/</website>
	</otherc>
</communication>
<hobbies>
	<likes>
		<music>English, Rock n' roll, pop, etc</music>
		<art>The ASCII Art</art>
		<sport>I hate sports, except chess</sport>
		<food>Veganism</food>
		<life>A empresary</life>
		<who enc="Base64">QWxvbmRyYQ</who>
		<color>Black, White</color>
		<schedule>Informatic</schedule>
		<moreay>*</moreay>
	</likes>
	<activities>
		<preferences>Computer, Reading, Programming</preferences>
		<projects>A programs PC</projects>
	</activities>
	<otherh>*</otherh>
</hobbies>
<file>
	<progsrc gt="y"/>
	<prog version="1.0">PC Garcil&reg; XML-ID Maker</nameprog>
	<instdir>%instdir%</instdir>
</file>
</vCardBatch>
